hadd ttbarMC_DL_triggerSF_newJECJER_v0_$1/outfile_ttbarMC_DL_triggerSF_newJECJER_v0_$1.root /eos/uscms/store/user/benjtann/ttbarMC_DL_triggerSF_newJECJER_v0_$1/ttbarMC_DL_triggerSF_newJECJER_v0_$1/MC/outfile_*.root
hadd ttbarMC_SL_triggerSF_newJECJER_v0_$1/outfile_ttbarMC_SL_triggerSF_newJECJER_v0_$1.root /eos/uscms/store/user/benjtann/ttbarMC_SL_triggerSF_newJECJER_v0_$1/ttbarMC_SL_triggerSF_newJECJER_v0_$1/MC/outfile_*.root

hadd MET_RunB_triggerSF_newJECJER_v0_$1/outfile_MET_RunB_triggerSF_newJECJER_v0_$1.root /eos/uscms/store/user/benjtann/MET_RunB_triggerSF_newJECJER_v0_$1/MET_RunB_triggerSF_newJECJER_v0_$1/data/outfile_*.root
hadd MET_RunC_triggerSF_newJECJER_v0_$1/outfile_MET_RunC_triggerSF_newJECJER_v0_$1.root /eos/uscms/store/user/benjtann/MET_RunC_triggerSF_newJECJER_v0_$1/MET_RunC_triggerSF_newJECJER_v0_$1/data/outfile_*.root
hadd MET_RunD_triggerSF_newJECJER_v0_$1/outfile_MET_RunD_triggerSF_newJECJER_v0_$1.root /eos/uscms/store/user/benjtann/MET_RunD_triggerSF_newJECJER_v0_$1/MET_RunD_triggerSF_newJECJER_v0_$1/data/outfile_*.root
hadd MET_RunE_triggerSF_newJECJER_v0_$1/outfile_MET_RunE_triggerSF_newJECJER_v0_$1.root /eos/uscms/store/user/benjtann/MET_RunE_triggerSF_newJECJER_v0_$1/MET_RunE_triggerSF_newJECJER_v0_$1/data/outfile_*.root
hadd MET_RunF_triggerSF_newJECJER_v0_$1/outfile_MET_RunF_triggerSF_newJECJER_v0_$1.root /eos/uscms/store/user/benjtann/MET_RunF_triggerSF_newJECJER_v0_$1/MET_RunF_triggerSF_newJECJER_v0_$1/data/outfile_*.root
   